
DEBUG: False
APP_BASE_URL: ''
SECRET_KEY: ''
ALLOWED_HOSTS: ['*']

DATABASE:
  NAME: 'postgres'
  USER: 'postgres'
  PASSWORD: ''
  HOST: 'db'
  PORT: 5432

VK_APP:
  ID: ''
  SECRET: ''
  SERVICE: ''

VK_ROOT:
  ID: ''
  VERSION: '5.84'
  SCOPE: 'wall,friends,photos,video,docs,notes,pages,status,groups,notifications,offline'